name: ecs-deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up AWS credentials
        run: |
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
      
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t my-app .

      - name: Tag Docker image
        run: |
          docker tag my-app:latest ${{ secrets.AWS_ECR_REGISTRY }}/ecs-ecr-repo:latest
      
      - name: Push Docker image to Amazon ECR
        run: |
          docker push ${{ secrets.AWS_ECR_REGISTRY }}/ecs-ecr-repo:latest
      
      - name: Update ECS Task Definition
        run: |
          aws ecs register-task-definition --cli-input-json file://task-def.json

      - name: Create or Update ECS Service
        run: |
          aws ecs create-service --cluster TestCluster --service-name s3-service --task-definition s3-interaction-task --launch-type FARGATE --desired-count 1 --network-configuration awsvpcConfiguration={subnets=[subnet-0f1aeda3182369e25],securityGroups=[sg-086f714fb49efe995],assignPublicIp=ENABLED}
