name: ecs-deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up AWS credentials
        run: |
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
      
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t my-app .

      - name: Tag Docker image
        run: |
          echo "ECR Registry: ${{ secrets.AWS_ECR_REGISTRY }}"
          docker tag my-app:latest 317327656978.dkr.ecr.us-east-1.amazonaws.com/ecs-ecr-repo:latest
      
      - name: Push Docker image to Amazon ECR
        run: |
          echo "ECR Registry: ${{ secrets.AWS_ECR_REGISTRY }}"
          docker push 317327656978.dkr.ecr.us-east-1.amazonaws.com/ecs-ecr-repo:latest
      
      - name: Check if ECS service exists
        id: check-service
        run: |
          aws ecs describe-services --cluster TestCluster --services s3-service >/dev/null 2>&1 || echo "::set-output name=exists::false"

      - name: Create or update ECS service
        if: steps.check-service.outputs.exists == 'false'
        run: |
          aws ecs create-service --cluster TestCluster --service-name s3-service --task-definition s3-interaction-task --launch-type FARGATE --desired-count 1 --network-configuration "awsvpcConfiguration={subnets=[subnet-0f1aeda3182369e25],securityGroups=[sg-086f714fb49efe995],assignPublicIp=ENABLED}"
        else
          aws ecs update-service --cluster TestCluster --service s3-service --task-definition arn:aws:ecs:***:317327656978:task-definition/s3-interaction-task:7 --network-configuration "awsvpcConfiguration={subnets=[subnet-0f1aeda3182369e25],securityGroups=[sg-086f714fb49efe995],assignPublicIp=ENABLED}"
